language: ruby
rvm:
- 2.0.0
- 2.1.6
- 2.2.2
gemfile:
- gemfiles/activemodel_3.gemfile
- gemfiles/rspec_3_0.gemfile
- gemfiles/rspec_3_1.gemfile
- gemfiles/rspec_3_2.gemfile
- gemfiles/rspec_3_3.gemfile
