# Build Options
language: ruby
rvm:
- 2.1.9
- 2.2.5
- 2.3.1
gemfile:
- gemfiles/activemodel_3.gemfile
- gemfiles/rspec_3_0.gemfile
- gemfiles/rspec_3_1.gemfile
- gemfiles/rspec_3_2.gemfile
- gemfiles/rspec_3_3.gemfile
- gemfiles/rspec_3_4.gemfile
- gemfiles/rspec_3_5.gemfile
matrix:
  allow_failures:
  - gemfile: gemfiles/rspec_edge.gemfile
  fast_finish: true
  include:
    - rvm: 2.3.1
      gemfile: gemfiles/rspec_edge.gemfile

# Travis-CI Configuration
cache: bundler
sudo:  false # Enable containerized builds.
